
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(ggplot2)
library(data.table)
library(dplyr)
#library(reshape2)
#library(RColorBrewer)
#library(viridis)
#library(caret)
#library(future)
#library(promises)
#library(doParallel)

source('functions.R')
#library(lime)
FORMATS <- c("examples", "standard")
MODELS <- c('rf','nnet','svmLinear','logreg','naive_bayes')
names(MODELS) <- c("Random Forest", "Neural Network", "Support Vector Machines with Linear Kernel",
                   "Logistic Regression", "Naive Bayes")