
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(markdown)
library(ggplot2)
#library(reshape2)
#library(RColorBrewer)
#library(viridis)
#library(caret)
#library(future)
#library(promises)
#library(doParallel)

MSstatsPackages <- c("data.table","dplyr")
lapply(MSstatsPackages, library, character.only = TRUE)
#source("scripts/convert_to_MSstats.R")
#source("scripts/ParSampleSizeCalculationClassification.R")
#source("scripts/GroupComparison.R")
#source("scripts/methods.R")
source('functions.R')
#library(lime)
FORMATS <- c("examples", "standard")
